create table if not exists catayst_fatca_workflow(
workflow_code Integer not null,
workflow_type varchar(255) null,
ref_id varchar(255) null,
screen_id varchar(255) null,
cr_id Integer null,
cr_type_code Integer null,
user_id Integer null,
key_atttr varchar(255) null,
cr_desc varchar(255) null,
ket_attr_value varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint catayst_fatca_workflow_pk primary key(workflow_code));